services:
  - type: web
    name: streamhub-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
